{
  "name": "Untitled",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Activities",
        "lineageTag": "c37944f4-85e2-42b1-b20c-42f06114f831",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "1af6b75a-af2e-4834-8d59-9fcbf1c25339",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Calories Burned",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Calories Burned",
            "formatString": "0",
            "lineageTag": "46db2a03-7c4f-457c-9a32-03e152915651",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Steps",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Steps",
            "formatString": "0",
            "lineageTag": "d5a80406-bf17-417b-a8ef-22cde64a331a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Distance",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Distance",
            "lineageTag": "2fff7403-02bd-45bd-9822-064b3a65794d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Floors",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Floors",
            "formatString": "0",
            "lineageTag": "5dc1f724-130b-4a92-b93d-fd4c054c9e67",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Minutes Sedentary",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Minutes Sedentary",
            "formatString": "0",
            "lineageTag": "59b3d97e-c9f1-4aab-bfd2-5bec078d9795",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Minutes Lightly Active",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Minutes Lightly Active",
            "formatString": "0",
            "lineageTag": "211be13c-71e5-41be-bb68-bd3c927785f8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Minutes Fairly Active",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Minutes Fairly Active",
            "formatString": "0",
            "lineageTag": "65ddaf4b-c31d-41fa-beda-75215ead657e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Minutes Very Active",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Minutes Very Active",
            "formatString": "0",
            "lineageTag": "48d6c855-844e-4fd1-b01f-9926ab155269",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Activity Calories",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Activity Calories",
            "formatString": "0",
            "lineageTag": "0684dbd4-ebe9-4b7c-a574-2d8d108ac1eb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Hours Sedentary",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Hours Sedentary",
            "lineageTag": "4af32bfb-a284-4e2b-b26e-e42c7b88bcd7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Hours Lightly Active",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Hours Lightly Active",
            "lineageTag": "fe4c7c5c-46c9-4fc7-be71-363bc5919dd5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Hours Fairly Active",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Hours Fairly Active",
            "lineageTag": "acad765a-689d-4c31-9f53-4afb88fbceb6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Hours Very Active",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Hours Very Active",
            "lineageTag": "37def820-8078-4704-987b-19d542ea5a23",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Activities-a89d0e9e-0ba1-4d44-a1c5-1ec49c1840f9",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/11lFmdNEIcEwYfDLIF5NFobygtvrUYWIhj60bQwo32AU/edit?usp=sharing\"),",
                "    Activities_Table = Source{[name=\"Activities\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Activities_Table, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Date\", type date}, {\"Calories Burned\", Int64.Type}, {\"Steps\", Int64.Type}, {\"Distance\", type number}, {\"Floors\", Int64.Type}, {\"Minutes Sedentary\", Int64.Type}, {\"Minutes Lightly Active\", Int64.Type}, {\"Minutes Fairly Active\", Int64.Type}, {\"Minutes Very Active\", Int64.Type}, {\"Activity Calories\", Int64.Type}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([Date] <> #date(2021, 7, 1) and [Date] <> #date(2021, 7, 2) and [Date] <> #date(2021, 7, 3) and [Date] <> #date(2021, 7, 4) and [Date] <> #date(2021, 7, 5) and [Date] <> #date(2021, 7, 6) and [Date] <> #date(2021, 7, 7) and [Date] <> #date(2021, 7, 8) and [Date] <> #date(2021, 7, 9) and [Date] <> #date(2021, 7, 10) and [Date] <> #date(2021, 7, 11) and [Date] <> #date(2021, 7, 12))),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Hours Sedentary\", each Number.Round([Minutes Sedentary] / 60, 1)),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"Hours Lightly Active\", each Number.Round([Minutes Lightly Active] / 60, 1)),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Added Custom1\", \"Hours Fairly Active\", each Number.Round([Minutes Fairly Active] / 60, 1)),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Added Custom2\", \"Hours Very Active\", each Number.Round([Minutes Very Active] / 60, 1)),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom3\",{{\"Hours Sedentary\", type number}, {\"Hours Lightly Active\", type number}, {\"Hours Fairly Active\", type number}, {\"Hours Very Active\", type number}})",
                "in",
                "    #\"Changed Type1\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sum of Minutes Sedentary",
            "description": "This measure is the sum of column 'Activities'[Minutes Sedentary]",
            "expression": "SUM('Activities'[Minutes Sedentary])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "ad21c57d-85f4-492f-b1f5-2b9e30de6e47",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Minutes Lightly Active",
            "description": "This measure is the sum of column 'Activities'[Minutes Lightly Active]",
            "expression": "SUM('Activities'[Minutes Lightly Active])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "e8810cf1-5ae2-4431-b503-846d30b39128",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Minutes Fairly Active",
            "description": "This measure is the sum of column 'Activities'[Minutes Fairly Active]",
            "expression": "SUM('Activities'[Minutes Fairly Active])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "12595984-c0e4-4a80-86b5-8e553b040b19",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Minutes Very Active",
            "description": "This measure is the sum of column 'Activities'[Minutes Very Active]",
            "expression": "SUM('Activities'[Minutes Very Active])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "0578d911-d1e1-4a32-9138-ccc0be9a148e",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Activity Calories",
            "description": "This measure is the sum of column 'Activities'[Activity Calories]",
            "expression": "SUM('Activities'[Activity Calories])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "3602c62b-c79b-4eb2-812c-690d9a8b7e92",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Hours Sedentary",
            "description": "This measure is the sum of column 'Activities'[Hours Sedentary]",
            "expression": "SUM('Activities'[Hours Sedentary])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "40e26fe1-1b27-4f72-b95c-6702f4040a2c",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Hours Lightly Active",
            "description": "This measure is the sum of column 'Activities'[Hours Lightly Active]",
            "expression": "SUM('Activities'[Hours Lightly Active])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "5a6b61f0-ce7e-4850-9806-48a06ae6fd3f",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Hours Fairly Active",
            "description": "This measure is the sum of column 'Activities'[Hours Fairly Active]",
            "expression": "SUM('Activities'[Hours Fairly Active])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "db29e747-8a98-4673-bf0f-6c4ad77f823b",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Hours Very Active",
            "description": "This measure is the sum of column 'Activities'[Hours Very Active]",
            "expression": "SUM('Activities'[Hours Very Active])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "ca06f33d-4b8b-440b-9028-df9d198bef3d",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Calories Burned",
            "description": "This measure is the sum of column 'Activities'[Calories Burned]",
            "expression": "SUM('Activities'[Calories Burned])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "7fc25d54-f851-4832-8a9f-c6f608a81418",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Steps",
            "description": "This measure is the sum of column 'Activities'[Steps]",
            "expression": "SUM('Activities'[Steps])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "8983309f-a28c-4868-8659-8b175cb0f826",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Distance",
            "description": "This measure is the sum of column 'Activities'[Distance]",
            "expression": "SUM('Activities'[Distance])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "3b8a62b7-0402-4033-b9a6-006466f5a876",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Floors",
            "description": "This measure is the sum of column 'Activities'[Floors]",
            "expression": "SUM('Activities'[Floors])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "03e1d18a-7ac7-469d-83f6-28590c36a116",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Avg of Calories Burned",
            "description": "This measure is the sum of column 'Activities'[Calories Burned]",
            "expression": "AVERAGE('Activities'[Calories Burned])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "d93b00ae-7607-4ffb-8491-701e342f5955",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Avg of Steps",
            "description": "This measure is the sum of column 'Activities'[Steps]",
            "expression": "AVERAGE('Activities'[Steps])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "ba38db18-4cd4-4a02-938a-3a0064b46b74"
          },
          {
            "name": "Avg of Distance",
            "description": "This measure is the sum of column 'Activities'[Distance]",
            "expression": "AVERAGE('Activities'[Distance])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "89d8ca1e-b073-4c79-9de3-bd77cfda9b84"
          },
          {
            "name": "Avg of Floors",
            "description": "This measure is the sum of column 'Activities'[Floors]",
            "expression": "AVERAGE('Activities'[Floors])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "1279eb5c-bd46-49b9-8274-a4565f93d959"
          },
          {
            "name": "Avg of Minutes Sedentary",
            "description": "This measure is the sum of column 'Activities'[Minutes Sedentary]",
            "expression": "AVERAGE('Activities'[Minutes Sedentary])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "b4f58bd7-c1a7-42aa-ba72-802ed3d9fa44"
          },
          {
            "name": "Avg of Minutes Lightly Active",
            "description": "This measure is the sum of column 'Activities'[Minutes Lightly Active]",
            "expression": "AVERAGE('Activities'[Minutes Lightly Active])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "2a2d42ce-c2c3-4090-a9f5-5605765591c8"
          },
          {
            "name": "Avg of Minutes Fairly Active",
            "description": "This measure is the sum of column 'Activities'[Minutes Fairly Active]",
            "expression": "AVERAGE('Activities'[Minutes Fairly Active])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "d37860ea-c1f0-4ad6-8af9-6097a254a165"
          },
          {
            "name": "Avg of Minutes Very Active",
            "description": "This measure is the sum of column 'Activities'[Minutes Very Active]",
            "expression": "AVERAGE('Activities'[Minutes Very Active])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "65015d0c-cd24-4568-8370-cde77394a897"
          },
          {
            "name": "Avg of Activity Calories",
            "description": "This measure is the sum of column 'Activities'[Activity Calories]",
            "expression": "AVERAGE('Activities'[Activity Calories])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "f372f285-6e7d-4870-98f6-6c4b9946dfcc",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Avg of Hours Sedentary",
            "description": "This measure is the sum of column 'Activities'[Hours Sedentary]",
            "expression": "AVERAGE('Activities'[Hours Sedentary])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "84a31ffb-58c2-4af1-98a4-2f30b2ac7c2e"
          },
          {
            "name": "Avg of Hours Lightly Active",
            "description": "This measure is the sum of column 'Activities'[Hours Lightly Active]",
            "expression": "AVERAGE('Activities'[Hours Lightly Active])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "ad7422ed-34a6-4731-9347-d20dc108186c"
          },
          {
            "name": "Avg of Hours Fairly Active",
            "description": "This measure is the sum of column 'Activities'[Hours Fairly Active]",
            "expression": "AVERAGE('Activities'[Hours Fairly Active])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "be286af0-67cd-4c74-a996-3dbf49f5a9c8"
          },
          {
            "name": "Avg of Hours Very Active",
            "description": "This measure is the sum of column 'Activities'[Hours Very Active]",
            "expression": "AVERAGE('Activities'[Hours Very Active])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "5118d35a-129d-41a2-ad0d-4a458d66fb5c"
          },
          {
            "name": "Avg Calories Burned - Prev Period",
            "expression": [
              "CALCULATE (",
              "    [Avg of Calories Burned],",
              "    DATESBETWEEN ( DimDate[Date], [Prev Period Start Date], [Prev Period End Date] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "_Measures\\Prev Period",
            "lineageTag": "d4d921f5-92fd-49a9-a3fd-c6a44ada772e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Activity Calories - Prev Period",
            "expression": [
              "CALCULATE (",
              "    [Avg of Activity Calories],",
              "    DATESBETWEEN ( DimDate[Date], [Prev Period Start Date], [Prev Period End Date] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "_Measures\\Prev Period",
            "lineageTag": "5575e9b0-52ce-4143-b13e-540583b0aabb",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Steps - Prev Period",
            "expression": [
              "CALCULATE (",
              "    [Avg of Steps],",
              "    DATESBETWEEN ( DimDate[Date], [Prev Period Start Date], [Prev Period End Date] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "_Measures\\Prev Period",
            "lineageTag": "861bc260-9495-4a69-83bc-45a73d3a1cdb",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg Calories Burned - PoP Growth %",
            "expression": [
              "",
              "VAR _PrevPeriod = [Avg Calories Burned - Prev Period] ",
              "VAR _Diff = [Avg of Calories Burned] - _PrevPeriod",
              "VAR _Res =",
              "    DIVIDE ( _Diff, _PrevPeriod )",
              "RETURN",
              "    _Res"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "_Measures\\PoP Growth %",
            "lineageTag": "8da7b34d-be7c-42ff-9cc7-70cd5a11636e",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg Activity Calories - PoP Growth %",
            "expression": [
              "",
              "VAR _PrevPeriod = [Avg Activity Calories - Prev Period]",
              "VAR _Diff = [Avg of Activity Calories] - _PrevPeriod",
              "VAR _Res =",
              "    DIVIDE ( _Diff, _PrevPeriod )",
              "RETURN",
              "    _Res"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "_Measures\\PoP Growth %",
            "lineageTag": "96bfc198-ead7-45d2-854b-6b65d23a9506",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg Steps - PoP Growth %",
            "expression": [
              "",
              "VAR _PrevPeriod = [Avg Steps - Prev Period] ",
              "VAR _Diff = [Avg of Steps] - _PrevPeriod",
              "VAR _Res =",
              "    DIVIDE ( _Diff, _PrevPeriod )",
              "RETURN",
              "    _Res"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "_Measures\\PoP Growth %",
            "lineageTag": "ffbe9160-7a75-4890-86f2-b104e01c3417",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg Calories Burned - Trend Indicator",
            "expression": [
              "",
              "VAR _Measure = ROUND( [Avg Calories Burned - PoP Growth %]*100, 1 )",
              "VAR _Up = UNICHAR ( 9650 ) & \" \" & _Measure & \"%\"",
              "VAR _Down = UNICHAR ( 9660 ) & \" \" & _Measure & \"%\"",
              "VAR _NoChange = UNICHAR ( 9654 ) & \" \" & \"0%\"",
              "VAR _Res = ",
              "SWITCH (",
              "    TRUE (),",
              "    _Measure > 0, _Up,",
              "    _Measure < 0, _Down,",
              "    -- else ",
              "    _NoChange",
              ")",
              "RETURN",
              "_Res"
            ],
            "displayFolder": "_Measures\\KPI Trend Indicator",
            "lineageTag": "a29efe77-d479-497c-9904-6da175f05968"
          },
          {
            "name": "Avg Activity Calories - Trend Indicator",
            "expression": [
              "",
              "VAR _Measure = ROUND( [Avg Activity Calories - PoP Growth %]*100, 1 )",
              "VAR _Up = UNICHAR ( 9650 ) & \" \" & _Measure & \"%\"",
              "VAR _Down = UNICHAR ( 9660 ) & \" \" & _Measure & \"%\"",
              "VAR _NoChange = UNICHAR ( 9654 ) & \" \" & \"0%\"",
              "VAR _Res = ",
              "SWITCH (",
              "    TRUE (),",
              "    _Measure > 0, _Up,",
              "    _Measure < 0, _Down,",
              "    -- else ",
              "    _NoChange",
              ")",
              "RETURN",
              "_Res"
            ],
            "displayFolder": "_Measures\\KPI Trend Indicator",
            "lineageTag": "49a60b99-8b00-4554-9676-51539add4275"
          },
          {
            "name": "Avg Steps - Trend Indicator",
            "expression": [
              "",
              "VAR _Measure = ROUND( [Avg Steps - PoP Growth %]*100, 1 )",
              "VAR _Up = UNICHAR ( 9650 ) & \" \" & _Measure & \"%\"",
              "VAR _Down = UNICHAR ( 9660 ) & \" \" & _Measure & \"%\"",
              "VAR _NoChange = UNICHAR ( 9654 ) & \" \" & \"0%\"",
              "VAR _Res = ",
              "SWITCH (",
              "    TRUE (),",
              "    _Measure > 0, _Up,",
              "    _Measure < 0, _Down,",
              "    -- else ",
              "    _NoChange",
              ")",
              "RETURN",
              "_Res"
            ],
            "displayFolder": "_Measures\\KPI Trend Indicator",
            "lineageTag": "abc13145-234f-4527-ab60-a9a5321b6198"
          },
          {
            "name": "Avg Calories Burned - Cond Color",
            "expression": [
              "",
              "VAR _Measure = [Avg Calories Burned - PoP Growth %]",
              "VAR _Up = \"Navy\"",
              "VAR _Down = \"DarkRed\"",
              "VAR _NoChange = \"DarkGray\"",
              "VAR _Res = ",
              "SWITCH (",
              "    TRUE (),",
              "    _Measure > 0, _Up,",
              "    _Measure < 0, _Down,",
              "    -- else ",
              "    _NoChange",
              ")",
              "RETURN",
              "_Res"
            ],
            "displayFolder": "_Measures\\KPI Trend Cond Color",
            "lineageTag": "7258a8ae-0480-40ac-a336-d0260185ab2c"
          },
          {
            "name": "Avg Activity Calories - Cond Color",
            "expression": [
              "",
              "VAR _Measure = [Avg Activity Calories - PoP Growth %]",
              "VAR _Up = \"Navy\"",
              "VAR _Down = \"DarkRed\"",
              "VAR _NoChange = \"DarkGray\"",
              "VAR _Res = ",
              "SWITCH (",
              "    TRUE (),",
              "    _Measure > 0, _Up,",
              "    _Measure < 0, _Down,",
              "    -- else ",
              "    _NoChange",
              ")",
              "RETURN",
              "_Res"
            ],
            "displayFolder": "_Measures\\KPI Trend Cond Color",
            "lineageTag": "adfe3826-5c03-460f-b09c-0b99d24ac17b"
          },
          {
            "name": "Avg Steps- Cond Color",
            "expression": [
              "",
              "VAR _Measure = [Avg Steps - PoP Growth %]",
              "VAR _Up = \"Navy\"",
              "VAR _Down = \"DarkRed\"",
              "VAR _NoChange = \"DarkGray\"",
              "VAR _Res = ",
              "SWITCH (",
              "    TRUE (),",
              "    _Measure > 0, _Up,",
              "    _Measure < 0, _Down,",
              "    -- else ",
              "    _NoChange",
              ")",
              "RETURN",
              "_Res"
            ],
            "displayFolder": "_Measures\\KPI Trend Cond Color",
            "lineageTag": "b3c9b951-3d24-44bd-a09f-63a2fe2bdb3e"
          },
          {
            "name": "Activity Goals",
            "expression": [
              "",
              "VAR _GoalCaloriesBurned = 2500",
              "VAR _GoalActivityCalories = 1000",
              "VAR _GoalSteps = 10000",
              "VAR _Res = ",
              "SWITCH( ",
              "    [Selected Activity],",
              "    \"Activity Calories\", _GoalActivityCalories,",
              "    \"Calories Burned\", _GoalCaloriesBurned,",
              "    \"Steps\", _GoalSteps",
              ")",
              "RETURN",
              "_Res"
            ],
            "formatString": "0",
            "displayFolder": "_Measures\\Dynamic Stuff",
            "lineageTag": "0f5b2fa3-1c78-47ce-a0e2-b3fa11336ce4"
          },
          {
            "name": "Selected Activity Measure",
            "expression": [
              "",
              "SWITCH( ",
              "    [Selected Activity],",
              "    \"Calories Burned\", [Avg of Calories Burned],",
              "    \"Activity Calories\", [Avg of Activity Calories],",
              "    \"Steps\", [Avg of Steps]",
              ")"
            ],
            "displayFolder": "_Measures\\Dynamic Stuff",
            "lineageTag": "686b9d53-34f6-4a53-807b-87676ba29443",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Selected Activity",
            "expression": "SELECTEDVALUE( 'Activities KPI Group'[Activites] )",
            "displayFolder": "_Measures\\Dynamic Stuff",
            "lineageTag": "7f53894d-a2d5-4475-b337-9fb3228ca897"
          },
          {
            "name": "Activity Cond Color",
            "expression": [
              "",
              "IF( ",
              "    [Activity Goals] < [Selected Activity Measure], \"#FFCB42\", \"#FFE69A\"",
              ")"
            ],
            "displayFolder": "_Measures\\Dynamic Stuff",
            "lineageTag": "e42eee44-d778-40bf-a180-cfdc50d9fb31"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Sleep",
        "lineageTag": "1e970f2a-761b-4da9-8665-6f4299df5fa5",
        "columns": [
          {
            "name": "Start Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Start Date",
            "formatString": "Long Date",
            "lineageTag": "d6eef988-8362-41f4-998b-c2aa050e8943",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "End Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "End Date",
            "formatString": "Long Date",
            "lineageTag": "f22e3c79-1661-4453-a2c9-0a1d9b051b24",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Minutes Asleep",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Minutes Asleep",
            "formatString": "0",
            "lineageTag": "a9bae361-9b45-41b9-8389-aaf57b6696f9",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Minutes Awake",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Minutes Awake",
            "formatString": "0",
            "lineageTag": "7b8fb51e-bee4-4eea-b856-a1cccdc36f49",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Number of Awakenings",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Number of Awakenings",
            "formatString": "0",
            "lineageTag": "a02296e8-8561-43d4-9148-77893bb1422b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Time in Bed",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Time in Bed",
            "formatString": "0",
            "lineageTag": "7a6d35f5-6879-4333-b86f-1c1df937c278",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Minutes REM Sleep",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Minutes REM Sleep",
            "formatString": "0",
            "lineageTag": "3a566490-92e1-453b-a5c1-d82a58ca4e1a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Minutes Light Sleep",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Minutes Light Sleep",
            "formatString": "0",
            "lineageTag": "836452c4-393e-4612-99fc-33c41cfb86ad",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Minutes Deep Sleep",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Minutes Deep Sleep",
            "formatString": "0",
            "lineageTag": "397efa73-04bc-49e5-a2ab-ff463a4537da",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Start Time",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Start Time",
            "formatString": "Long Time",
            "lineageTag": "9429321d-0f24-4239-b516-f64c3484c747",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "End Time",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "End Time",
            "formatString": "Long Time",
            "lineageTag": "d707d2d6-e984-44a2-a484-3f1cf9b2d77a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Hours Asleep",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Hours Asleep",
            "lineageTag": "d3eb3b12-92ef-4ff0-a9e5-5cafe39453c2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Hours Awake",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Hours Awake",
            "lineageTag": "3a95b81b-44d8-4563-9dec-9c95a9766c16",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Hours in Bed",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Hours in Bed",
            "lineageTag": "f3cfe318-6eb4-4af7-9ecf-7fe4e696b6a4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Hours REM Sleep",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Hours REM Sleep",
            "lineageTag": "25a23f10-0b0e-46f4-8dc7-db6df3dd2a4b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Hours Light Sleep",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Hours Light Sleep",
            "lineageTag": "53a30c9f-9809-450d-8cc7-5bc6455dc5a0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Hours Deep Sleep",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Hours Deep Sleep",
            "lineageTag": "51f6cfc4-2fdc-4b19-a490-d8656c3ff5c2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sleep-7c4c5b7f-11ed-474d-ae08-f42e58e1021f",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/11lFmdNEIcEwYfDLIF5NFobygtvrUYWIhj60bQwo32AU/edit?usp=sharing\"),",
                "    Sleep_Table = Source{[name=\"Sleep\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sleep_Table, [PromoteAllScalars=true]),",
                "    #\"Duplicate Start Time\" = Table.DuplicateColumn(#\"Promoted Headers\", \"Start Time\", \"Start Time - Copy\"),",
                "    #\"Duplicated End Time\" = Table.DuplicateColumn(#\"Duplicate Start Time\", \"End Time\", \"End Time - Copy\"),",
                "    #\"Extracted Date\" = Table.TransformColumns(#\"Duplicated End Time\",{{\"Start Time\", DateTime.Date, type date}, {\"End Time\", DateTime.Date, type date}}),",
                "    #\"Extracted Time\" = Table.TransformColumns(#\"Extracted Date\",{{\"Start Time - Copy\", DateTime.Time, type time}, {\"End Time - Copy\", DateTime.Time, type time}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Extracted Time\",\"N/A\",null,Replacer.ReplaceValue,{\"Minutes REM Sleep\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"N/A\",null,Replacer.ReplaceValue,{\"Minutes Light Sleep\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"N/A\",null,Replacer.ReplaceValue,{\"Minutes Deep Sleep\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value2\",{{\"Minutes Asleep\", Int64.Type}, {\"Minutes Awake\", Int64.Type}, {\"Number of Awakenings\", Int64.Type}, {\"Time in Bed\", Int64.Type}, {\"Minutes REM Sleep\", Int64.Type}, {\"Minutes Light Sleep\", Int64.Type}, {\"Minutes Deep Sleep\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Start Time\", \"Start Date\"}, {\"End Time\", \"End Date\"}, {\"Start Time - Copy\", \"Start Time\"}, {\"End Time - Copy\", \"End Time\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"Hours Asleep\", each Number.Round([Minutes Asleep] / 60, 1)),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"Hours Awake\", each Number.Round([Minutes Awake] / 60, 1)),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Added Custom1\", \"Hours in Bed\", each Number.Round([Time in Bed] / 60, 1)),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Added Custom2\", \"Hours REM Sleep\", each Number.Round([Minutes REM Sleep] / 60, 1)),",
                "    #\"Added Custom4\" = Table.AddColumn(#\"Added Custom3\", \"Hours Light Sleep\", each Number.Round([Minutes Light Sleep] / 60, 1)),",
                "    #\"Added Custom5\" = Table.AddColumn(#\"Added Custom4\", \"Hours Deep Sleep\", each Number.Round([Minutes Deep Sleep] / 60, 1)),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom5\",{{\"Hours Asleep\", type number}, {\"Hours Awake\", type number}, {\"Hours in Bed\", type number}, {\"Hours Light Sleep\", type number}, {\"Hours REM Sleep\", type number}, {\"Hours Deep Sleep\", type number}})",
                "in",
                "    #\"Changed Type1\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sum of Minutes Asleep",
            "description": "This measure is the sum of column 'Sleep'[Minutes Asleep]",
            "expression": "SUM('Sleep'[Minutes Asleep])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "c6b0eb98-f09d-4b76-9d43-8c15b02d5d89",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Minutes Awake",
            "description": "This measure is the sum of column 'Sleep'[Minutes Awake]",
            "expression": "SUM('Sleep'[Minutes Awake])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "b964a8e3-254c-4ac4-bc0b-d5da7ff1077b",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Time in Bed",
            "description": "This measure is the sum of column 'Sleep'[Time in Bed]",
            "expression": "SUM('Sleep'[Time in Bed])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "e296f483-6d54-4263-83d9-487ca9f5712d",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Minutes REM Sleep",
            "description": "This measure is the sum of column 'Sleep'[Minutes REM Sleep]",
            "expression": "SUM('Sleep'[Minutes REM Sleep])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "581d2000-1871-4822-adf4-b8b468d22f7e",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Number of Awakenings",
            "description": "This measure is the sum of column 'Sleep'[Number of Awakenings]",
            "expression": "SUM('Sleep'[Number of Awakenings])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "4772fcfb-59ea-479b-a2be-24703affae5e",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Minutes Light Sleep",
            "description": "This measure is the sum of column 'Sleep'[Minutes Light Sleep]",
            "expression": "SUM('Sleep'[Minutes Light Sleep])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "d3bbe7c5-4868-4daa-b993-1932f2a0a776",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Minutes Deep Sleep",
            "description": "This measure is the sum of column 'Sleep'[Minutes Deep Sleep]",
            "expression": "SUM('Sleep'[Minutes Deep Sleep])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "90bfc022-cd50-477d-8142-99e754757652",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Hours Asleep",
            "description": "This measure is the sum of column 'Sleep'[Hours Asleep]",
            "expression": "SUM('Sleep'[Hours Asleep])",
            "formatString": "#,0.0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "a3ca35a4-16ce-492c-be1d-1be3a2bff5d1",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\",\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Sum of Hours Awake",
            "description": "This measure is the sum of column 'Sleep'[Hours Awake]",
            "expression": "SUM('Sleep'[Hours Awake])",
            "formatString": "#,0.0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "8996d657-7c7b-4090-b15d-78f94b68b2b7",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Sum of Hours in Bed",
            "description": "This measure is the sum of column 'Sleep'[Hours in Bed]",
            "expression": "SUM('Sleep'[Hours in Bed])",
            "formatString": "#,0.0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "315b4507-44d7-4399-a05b-0482d6bff0fb",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\",\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Sum of Hours REM Sleep",
            "description": "This measure is the sum of column 'Sleep'[Hours REM Sleep]",
            "expression": "SUM('Sleep'[Hours REM Sleep])",
            "formatString": "#,0.0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "24e8f536-2cbe-4995-9bcf-49d3e4ff947a",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\",\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Sum of Hours Light Sleep",
            "description": "This measure is the sum of column 'Sleep'[Hours Light Sleep]",
            "expression": "SUM('Sleep'[Hours Light Sleep])",
            "formatString": "#,0.0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "c1944f45-4223-457a-a35b-a30ce94a7f4f",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\",\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg of Minutes Asleep",
            "description": "This measure is the sum of column 'Sleep'[Minutes Asleep]",
            "expression": "AVERAGE('Sleep'[Minutes Asleep])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "d550f3d2-82ef-4c1d-a5a9-5ab8c3efcaf4",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Avg of Minutes Awake",
            "description": "This measure is the sum of column 'Sleep'[Minutes Awake]",
            "expression": "AVERAGE('Sleep'[Minutes Awake])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "a2e52bb7-e132-43b8-9cdf-4f538c841d88"
          },
          {
            "name": "Avg of Number of Awakenings",
            "description": "This measure is the sum of column 'Sleep'[Number of Awakenings]",
            "expression": "AVERAGE('Sleep'[Number of Awakenings])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "466b9fdc-3648-40c2-8486-1dd6d9dfea14"
          },
          {
            "name": "Avg of Time in Bed",
            "description": "This measure is the sum of column 'Sleep'[Time in Bed]",
            "expression": "AVERAGE('Sleep'[Time in Bed])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "452d7426-e645-482b-9e64-c998607ccf7b"
          },
          {
            "name": "Avg of Minutes REM Sleep",
            "description": "This measure is the sum of column 'Sleep'[Minutes REM Sleep]",
            "expression": "AVERAGE('Sleep'[Minutes REM Sleep])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "573e171e-73a1-4105-8d1f-1074019a4608"
          },
          {
            "name": "Avg of Minutes Light Sleep",
            "description": "This measure is the sum of column 'Sleep'[Minutes Light Sleep]",
            "expression": "AVERAGE('Sleep'[Minutes Light Sleep])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "3341eaa5-5e74-42f6-bd09-4562522b59cc"
          },
          {
            "name": "Avg of Minutes Deep Sleep",
            "description": "This measure is the sum of column 'Sleep'[Minutes Deep Sleep]",
            "expression": "AVERAGE('Sleep'[Minutes Deep Sleep])",
            "formatString": "#,0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "39a3c28f-f090-44ba-a995-9cbe51b948e2"
          },
          {
            "name": "Avg of Hours Asleep",
            "description": "This measure is the sum of column 'Sleep'[Hours Asleep]",
            "expression": "AVERAGE('Sleep'[Hours Asleep])",
            "formatString": "#,0.0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "e232d490-fc33-495a-ac0b-d742bae0f269",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg of Hours Awake",
            "description": "This measure is the sum of column 'Sleep'[Hours Awake]",
            "expression": "AVERAGE('Sleep'[Hours Awake])",
            "formatString": "#,0.0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "afd45b7f-1ef2-4b32-87a3-3149b5884f9d",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg of Hours in Bed",
            "description": "This measure is the sum of column 'Sleep'[Hours in Bed]",
            "expression": "AVERAGE('Sleep'[Hours in Bed])",
            "formatString": "#,0.0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "30797f9e-aca0-478d-a993-4ed60114765a",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg of Hours REM Sleep",
            "description": "This measure is the sum of column 'Sleep'[Hours REM Sleep]",
            "expression": "AVERAGE('Sleep'[Hours REM Sleep])",
            "formatString": "#,0.0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "ef848014-3c0f-4ce2-aaab-16e89c43ee4f",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg of Hours Light Sleep",
            "description": "This measure is the sum of column 'Sleep'[Hours Light Sleep]",
            "expression": "AVERAGE('Sleep'[Hours Light Sleep])",
            "formatString": "#,0.0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "69a8cd29-430b-42ba-8adf-122f350cefa9",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg Time in Bed - Formatted",
            "expression": [
              "",
              "VAR _Measure = [Avg of Hours in Bed]",
              "VAR _Len =",
              "    LEN ( _Measure )",
              "VAR NotEdgeCase = _Len > 1",
              "VAR _Index =",
              "    IF ( NotEdgeCase, FIND ( \".\", _Measure ) - 1, 1 )",
              "VAR _Left =",
              "    LEFT ( _Measure, _Index )",
              "VAR _Right =",
              "    IF ( NotEdgeCase, RIGHT ( _Measure, _Len - _Index ), 0 )",
              "VAR _RightConsolidated =",
              "    ROUND ( _Right * 60, 0 )",
              "VAR _Combined = _Left & \"hr \" & _RightConsolidated & \"min\"",
              "VAR _Res =",
              "    SWITCH (",
              "        TRUE (),",
              "        _Left = \"0\", _RightConsolidated & \"min\",",
              "        _Right = 0, _Left & \"hr\",",
              "        _Combined",
              "    )",
              "RETURN",
              "    _Res"
            ],
            "displayFolder": "_Measures\\Formatted",
            "lineageTag": "c1c83d24-73f7-45ab-91b5-037ba23ebcbe",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg Time Deep Sleep - Formatted",
            "expression": [
              "",
              "VAR _Measure = [Avg of Hours Deep Sleep]",
              "VAR _Len =",
              "    LEN ( _Measure )",
              "VAR NotEdgeCase = _Len > 1",
              "VAR _Index =",
              "    IF ( NotEdgeCase, FIND ( \".\", _Measure ) - 1, 1 )",
              "VAR _Left =",
              "    LEFT ( _Measure, _Index )",
              "VAR _Right =",
              "    IF ( NotEdgeCase, RIGHT ( _Measure, _Len - _Index ), 0 )",
              "VAR _RightConsolidated =",
              "    ROUND ( _Right * 60, 0 )",
              "VAR _Combined = _Left & \"hr \" & _RightConsolidated & \"min\"",
              "VAR _Res =",
              "    SWITCH (",
              "        TRUE (),",
              "        _Left = \"0\", _RightConsolidated & \"min\",",
              "        _Right = 0, _Left & \"hr\",",
              "        _Combined",
              "    )",
              "RETURN",
              "    _Res"
            ],
            "displayFolder": "_Measures\\Formatted",
            "lineageTag": "c60030fe-0bf0-42c2-859f-0c63c36e4083",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg Time Awake - Formatted",
            "expression": [
              "",
              "VAR _Measure = [Avg of Hours Awake]",
              "VAR _Len =",
              "    LEN ( _Measure )",
              "VAR NotEdgeCase = _Len > 1",
              "VAR _Index =",
              "    IF ( NotEdgeCase, FIND ( \".\", _Measure ) - 1, 1 )",
              "VAR _Left =",
              "    LEFT ( _Measure, _Index )",
              "VAR _Right =",
              "    IF ( NotEdgeCase, RIGHT ( _Measure, _Len - _Index ), 0 )",
              "VAR _RightConsolidated =",
              "    ROUND ( _Right * 60, 0 )",
              "VAR _Combined = _Left & \"hr \" & _RightConsolidated & \"min\"",
              "VAR _Res =",
              "    SWITCH (",
              "        TRUE (),",
              "        _Left = \"0\", _RightConsolidated & \"min\",",
              "        _Right = 0, _Left & \"hr\",",
              "        _Combined",
              "    )",
              "RETURN",
              "    _Res"
            ],
            "displayFolder": "_Measures\\Formatted",
            "lineageTag": "87dfc9f8-1db0-41d8-bcf8-2d85c915edfc",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg Time Asleep - Formatted",
            "expression": [
              "",
              "VAR _Measure = [Avg of Hours Asleep]",
              "VAR _Len =",
              "    LEN ( _Measure )",
              "VAR NotEdgeCase = _Len > 1",
              "VAR _Index =",
              "    IF ( NotEdgeCase, FIND ( \".\", _Measure ) - 1, 1 )",
              "VAR _Left =",
              "    LEFT ( _Measure, _Index )",
              "VAR _Right =",
              "    IF ( NotEdgeCase, RIGHT ( _Measure, _Len - _Index ), 0 )",
              "VAR _RightConsolidated =",
              "    ROUND ( _Right * 60, 0 )",
              "VAR _Combined = _Left & \"hr \" & _RightConsolidated & \"min\"",
              "VAR _Res =",
              "    SWITCH (",
              "        TRUE (),",
              "        _Left = \"0\", _RightConsolidated & \"min\",",
              "        _Right = 0, _Left & \"hr\",",
              "        _Combined",
              "    )",
              "RETURN",
              "    _Res"
            ],
            "displayFolder": "_Measures\\Formatted",
            "lineageTag": "d047bbfd-83b7-4406-b3ea-029e24f789ec",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Sum of Hours Deep Sleep",
            "description": "This measure is the sum of column 'Sleep'[Hours Asleep]",
            "expression": "SUM('Sleep'[Hours Deep Sleep])",
            "formatString": "#,0.0",
            "displayFolder": "_Measures\\Base\\SUM",
            "lineageTag": "e7b963df-d1bf-48d2-81ba-88e796b1f76c",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\",\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg of Hours Deep Sleep",
            "description": "This measure is the sum of column 'Sleep'[Hours REM Sleep]",
            "expression": "AVERAGE('Sleep'[Hours Deep Sleep])",
            "formatString": "#,0.0",
            "displayFolder": "_Measures\\Base\\AVG",
            "lineageTag": "7c7a3622-0493-4057-83e4-adecea72e0e2",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg of Hours Asleep - Prev Period",
            "expression": [
              "CALCULATE (",
              "    [Avg of Hours Asleep],",
              "    DATESBETWEEN ( DimDate[Date], [Prev Period Start Date], [Prev Period End Date] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "_Measures\\Prev Period",
            "lineageTag": "94bffb99-c1c7-4e39-afb5-76c9ea98618a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg of Hours Deep Sleep - Prev Period",
            "expression": [
              "CALCULATE (",
              "    [Avg of Hours Deep Sleep],",
              "    DATESBETWEEN ( DimDate[Date], [Prev Period Start Date], [Prev Period End Date] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "_Measures\\Prev Period",
            "lineageTag": "3f42d52b-31a7-45d0-9f08-f28129bd8b29",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg of Hours Awake - Prev Period",
            "expression": [
              "CALCULATE (",
              "    [Avg of Hours Awake],",
              "    DATESBETWEEN ( DimDate[Date], [Prev Period Start Date], [Prev Period End Date] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "_Measures\\Prev Period",
            "lineageTag": "fd9c28c4-b173-47e8-8d9f-ce9c092a48d0",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Avg of Hours Asleep - PoP Growth %",
            "expression": [
              "",
              "VAR _PrevPeriod = [Avg of Hours Asleep - Prev Period] ",
              "VAR _Diff = [Avg of Hours Asleep] - _PrevPeriod",
              "VAR _Res =",
              "    DIVIDE ( _Diff, _PrevPeriod )",
              "RETURN",
              "    _Res"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "_Measures\\PoP Growth %",
            "lineageTag": "fd351e24-b9c7-47c1-ae94-59adfadc3f07",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg of Hours Deep Sleep - PoP Growth %",
            "expression": [
              "",
              "VAR _PrevPeriod = [Avg of Hours Deep Sleep - Prev Period]",
              "VAR _Diff = [Avg of Hours Deep Sleep] - _PrevPeriod",
              "VAR _Res =",
              "    DIVIDE ( _Diff, _PrevPeriod )",
              "RETURN",
              "    _Res"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "_Measures\\PoP Growth %",
            "lineageTag": "fd921592-2692-4448-a689-ee5e96e2691c",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg of Hours Awake - PoP Growth %",
            "expression": [
              "",
              "VAR _PrevPeriod = [Avg of Hours Awake - Prev Period] ",
              "VAR _Diff = [Avg of Hours Awake] - _PrevPeriod",
              "VAR _Res =",
              "    DIVIDE ( _Diff, _PrevPeriod )",
              "RETURN",
              "    _Res"
            ],
            "formatString": "0%;-0%;0%",
            "displayFolder": "_Measures\\PoP Growth %",
            "lineageTag": "a824b9c7-980e-4a02-aaaa-93685c341656",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Avg of Hours Asleep - Trend Indicator",
            "expression": [
              "",
              "VAR _Measure = ROUND( [Avg of Hours Asleep - PoP Growth %]*100, 1 )",
              "VAR _Up = UNICHAR ( 9650 ) & \" \" & _Measure & \"%\"",
              "VAR _Down = UNICHAR ( 9660 ) & \" \" & _Measure & \"%\"",
              "VAR _NoChange = UNICHAR ( 9654 ) & \" \" & \"0%\"",
              "VAR _Res = ",
              "SWITCH (",
              "    TRUE (),",
              "    _Measure > 0, _Up,",
              "    _Measure < 0, _Down,",
              "    -- else ",
              "    _NoChange",
              ")",
              "RETURN",
              "_Res"
            ],
            "displayFolder": "_Measures\\KPI Trend Indicator",
            "lineageTag": "70b5809f-343c-419f-863a-588202b26e10"
          },
          {
            "name": "Avg of Hours Deep Sleep - Trend Indicator",
            "expression": [
              "",
              "VAR _Measure = ROUND( [Avg of Hours Deep Sleep - PoP Growth %]*100, 1 )",
              "VAR _Up = UNICHAR ( 9650 ) & \" \" & _Measure & \"%\"",
              "VAR _Down = UNICHAR ( 9660 ) & \" \" & _Measure & \"%\"",
              "VAR _NoChange = UNICHAR ( 9654 ) & \" \" & \"0%\"",
              "VAR _Res = ",
              "SWITCH (",
              "    TRUE (),",
              "    _Measure > 0, _Up,",
              "    _Measure < 0, _Down,",
              "    -- else ",
              "    _NoChange",
              ")",
              "RETURN",
              "_Res"
            ],
            "displayFolder": "_Measures\\KPI Trend Indicator",
            "lineageTag": "1c76d593-1701-46e0-84d8-ad03b325a376"
          },
          {
            "name": "Avg of Hours Awake - Trend Indicator",
            "expression": [
              "",
              "VAR _Measure = ROUND( [Avg of Hours Awake - PoP Growth %]*100, 1 )",
              "VAR _Up = UNICHAR ( 9650 ) & \" \" & _Measure & \"%\"",
              "VAR _Down = UNICHAR ( 9660 ) & \" \" & _Measure & \"%\"",
              "VAR _NoChange = UNICHAR ( 9654 ) & \" \" & \"0%\"",
              "VAR _Res = ",
              "SWITCH (",
              "    TRUE (),",
              "    _Measure > 0, _Up,",
              "    _Measure < 0, _Down,",
              "    -- else ",
              "    _NoChange",
              ")",
              "RETURN",
              "_Res"
            ],
            "displayFolder": "_Measures\\KPI Trend Indicator",
            "lineageTag": "a5a77522-4977-44a7-9991-41097bef8a1a"
          },
          {
            "name": "Avg of Hours Asleep - Cond Color",
            "expression": [
              "",
              "VAR _Measure = [Avg of Hours Asleep - PoP Growth %]",
              "VAR _Up = \"Navy\"",
              "VAR _Down = \"DarkRed\"",
              "VAR _NoChange = \"DarkGray\"",
              "VAR _Res = ",
              "SWITCH (",
              "    TRUE (),",
              "    _Measure > 0, _Up,",
              "    _Measure < 0, _Down,",
              "    -- else ",
              "    _NoChange",
              ")",
              "RETURN",
              "_Res"
            ],
            "displayFolder": "_Measures\\KPI Trend Cond Color",
            "lineageTag": "63f1e1ff-7f87-41dc-bd54-8bb82cd44431"
          },
          {
            "name": "Avg of Hours Deep Sleep - Cond Color",
            "expression": [
              "",
              "VAR _Measure = [Avg of Hours Deep Sleep - PoP Growth %]",
              "VAR _Up = \"Navy\"",
              "VAR _Down = \"DarkRed\"",
              "VAR _NoChange = \"DarkGray\"",
              "VAR _Res = ",
              "SWITCH (",
              "    TRUE (),",
              "    _Measure > 0, _Up,",
              "    _Measure < 0, _Down,",
              "    -- else ",
              "    _NoChange",
              ")",
              "RETURN",
              "_Res"
            ],
            "displayFolder": "_Measures\\KPI Trend Cond Color",
            "lineageTag": "8dd67e43-1326-4b7c-998e-3d014df40b80"
          },
          {
            "name": "Avg of Hours Awake - Cond Color",
            "expression": [
              "",
              "VAR _Measure = [Avg of Hours Awake - PoP Growth %]",
              "VAR _Up = \"Navy\"",
              "VAR _Down = \"DarkRed\"",
              "VAR _NoChange = \"DarkGray\"",
              "VAR _Res = ",
              "SWITCH (",
              "    TRUE (),",
              "    _Measure > 0, _Up,",
              "    _Measure < 0, _Down,",
              "    -- else ",
              "    _NoChange",
              ")",
              "RETURN",
              "_Res"
            ],
            "displayFolder": "_Measures\\KPI Trend Cond Color",
            "lineageTag": "5995738d-0487-449a-8576-8b3ece19a0f2"
          },
          {
            "name": "Sleep Goals",
            "expression": [
              "",
              "VAR _GoalHoursAsleep = 8",
              "VAR _GoalHoursDeepSleep = 1.5",
              "VAR _GoalHoursAwake = 0.5",
              "VAR _Res = ",
              "SWITCH( ",
              "    [Selected Sleep],",
              "    \"Hours Asleep\", _GoalHoursAsleep,",
              "    \"Hours Deep Sleep\", _GoalHoursDeepSleep,",
              "    \"Hours Awake\", _GoalHoursAwake",
              ")",
              "RETURN",
              "_Res"
            ],
            "formatString": "0",
            "displayFolder": "_Measures\\Dynamic Stuff",
            "lineageTag": "abb742e4-83fc-4c49-b2d6-e59bbef4ad10"
          },
          {
            "name": "Selected Sleep Measure",
            "expression": [
              "",
              "SWITCH( ",
              "    [Selected Sleep],",
              "    \"Hours Asleep\", [Avg of Hours Asleep],",
              "    \"Hours Deep Sleep\", [Avg of Hours Deep Sleep],",
              "    \"Hours Awake\", [Avg of Hours Awake]",
              ")"
            ],
            "displayFolder": "_Measures\\Dynamic Stuff",
            "lineageTag": "c4285d27-8e6b-4393-8058-21a778a6d4a7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Selected Sleep",
            "expression": "SELECTEDVALUE( 'Sleep KPI Group'[Sleep Metrics] )",
            "displayFolder": "_Measures\\Dynamic Stuff",
            "lineageTag": "8395422f-55f8-428a-857a-3be018178b7e"
          },
          {
            "name": "Sleep Cond Color",
            "expression": [
              "",
              "IF (",
              "    [Selected Sleep] <> \"Hours Awake\",",
              "    IF ( [Sleep Goals] < [Selected Sleep Measure], \"#3974B0\", \"#CBDAE9\" ),",
              "    IF ( [Sleep Goals] < [Selected Sleep Measure], \"#CBDAE9\", \"#3974B0\" )",
              ")"
            ],
            "displayFolder": "_Measures\\Dynamic Stuff",
            "lineageTag": "616a3594-e82f-40fe-9cfb-8e2594fec6c4"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DimDate",
        "lineageTag": "1b8d312f-4176-4483-ba9d-5ede525f9be0",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "formatString": "Short Date",
            "lineageTag": "e8bef4d1-8e93-422c-b0cc-c150723a8fd0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\",\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "2a9cf754-b1aa-4699-a982-4d8d39ef6adc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Start of Year",
            "dataType": "dateTime",
            "sourceColumn": "Start of Year",
            "formatString": "Long Date",
            "lineageTag": "53605957-8ecc-4077-894c-1730d94fc634",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "End of Year",
            "dataType": "dateTime",
            "sourceColumn": "End of Year",
            "formatString": "Long Date",
            "lineageTag": "662cfbcb-05cd-4b41-a404-92d3e3c9568d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "sourceColumn": "Month Number",
            "formatString": "0",
            "lineageTag": "aee62833-5488-4a6f-a0f6-b0de8ed70e03",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Start of Month",
            "dataType": "dateTime",
            "sourceColumn": "Start of Month",
            "formatString": "Long Date",
            "lineageTag": "784ac02c-3a62-40f0-8acc-b30480a2e7e8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "End of Month",
            "dataType": "dateTime",
            "sourceColumn": "End of Month",
            "formatString": "Long Date",
            "lineageTag": "38d29022-bf82-4f8f-8a59-29e91f5c6a82",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Days in Month",
            "dataType": "int64",
            "sourceColumn": "Days in Month",
            "formatString": "0",
            "lineageTag": "becdc8db-25b5-45b3-bb82-1022d6b4c9cf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Day",
            "dataType": "int64",
            "sourceColumn": "Day",
            "formatString": "0",
            "lineageTag": "c82133d2-0c91-49ff-aa9d-8df84eadf845",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Day Name",
            "dataType": "string",
            "sourceColumn": "Day Name",
            "lineageTag": "3e65cd5c-fad0-41d0-872e-2cad67f285c6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Day of Week",
            "dataType": "int64",
            "sourceColumn": "Day of Week",
            "formatString": "0",
            "lineageTag": "7c420938-c84b-438d-8a11-ee54523ea961",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Day of Year",
            "dataType": "int64",
            "sourceColumn": "Day of Year",
            "formatString": "0",
            "lineageTag": "2fd18067-ec1a-4ec8-82af-0867fbac79a9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "lineageTag": "0bbc87ec-c971-4409-a10f-4ecb82d5e41b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Quarter Number",
            "dataType": "int64",
            "sourceColumn": "Quarter Number",
            "formatString": "0",
            "lineageTag": "2c648d52-0e26-49b3-8810-498b2430b7f5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "lineageTag": "ccd44017-fc42-4bb0-b63f-c88ddce7bb3c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Start of Quarter",
            "dataType": "dateTime",
            "sourceColumn": "Start of Quarter",
            "formatString": "Long Date",
            "lineageTag": "5f5a1519-ef61-441d-a640-30172a5afa07",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "End of Quarter",
            "dataType": "dateTime",
            "sourceColumn": "End of Quarter",
            "formatString": "Long Date",
            "lineageTag": "7bff5092-a72f-4acf-acc4-58f8bcbefa2e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Week of Year",
            "dataType": "int64",
            "sourceColumn": "Week of Year",
            "formatString": "0",
            "lineageTag": "9ddb68d8-8f9a-418f-b1a9-b8f54b459837",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Week of Month",
            "dataType": "int64",
            "sourceColumn": "Week of Month",
            "formatString": "0",
            "lineageTag": "b8f2c59f-bb7b-4090-8502-13811706d0f4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Start of Week",
            "dataType": "dateTime",
            "sourceColumn": "Start of Week",
            "formatString": "Long Date",
            "lineageTag": "6ab593b3-29a9-4cd2-8b71-85c2c2082519",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "End of Week",
            "dataType": "dateTime",
            "sourceColumn": "End of Week",
            "formatString": "Long Date",
            "lineageTag": "5e423c6c-8004-4da6-9349-34a4f19f9af2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Fiscal Year",
            "dataType": "int64",
            "sourceColumn": "Fiscal Year",
            "formatString": "0",
            "lineageTag": "386e8997-cf87-4dbd-9e87-65327fba9b81",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Fiscal Quarter",
            "dataType": "int64",
            "sourceColumn": "Fiscal Quarter",
            "formatString": "0",
            "lineageTag": "323fcd99-ee5b-4bde-a1fe-5114e9e47bbc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Fiscal Month",
            "dataType": "int64",
            "sourceColumn": "Fiscal Month",
            "formatString": "0",
            "lineageTag": "bd8a23e5-c994-4e24-8880-75c344570748",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Day Offset",
            "dataType": "int64",
            "sourceColumn": "Day Offset",
            "formatString": "0",
            "lineageTag": "b883a349-2137-46fe-871c-12aa63f910a8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Month Offset",
            "dataType": "int64",
            "sourceColumn": "Month Offset",
            "formatString": "0",
            "lineageTag": "53115620-55b1-498a-a41d-92bbf8bffdec",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Year Offset",
            "dataType": "int64",
            "sourceColumn": "Year Offset",
            "formatString": "0",
            "lineageTag": "edd6b940-daaa-4809-bad1-0d22ba4a12c9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Quarter Offset",
            "dataType": "int64",
            "sourceColumn": "Quarter Offset",
            "formatString": "0",
            "lineageTag": "01f8f1b7-5eb3-405e-b280-34f18c6fac3b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DimDate-a78f3dfa-251a-4c52-bd7a-1907025028b5",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"ce738073-c7d7-4aed-83cf-1d7620d60f29\" = Workspaces{[workspaceId=\"ce738073-c7d7-4aed-83cf-1d7620d60f29\"]}[Data],",
                "    #\"8c71201e-c086-4681-be62-e62c927a70dd\" = #\"ce738073-c7d7-4aed-83cf-1d7620d60f29\"{[dataflowId=\"8c71201e-c086-4681-be62-e62c927a70dd\"]}[Data],",
                "    DimDate_ = #\"8c71201e-c086-4681-be62-e62c927a70dd\"{[entity=\"DimDate\",version=\"\"]}[Data]",
                "in",
                "    DimDate_"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Curr Period Start Date",
            "expression": "FIRSTDATE( DimDate[Date] )",
            "displayFolder": "_Measures\\Period Start End Dates",
            "lineageTag": "bd2ebbc6-f729-4713-96bf-4e91e72451b9"
          },
          {
            "name": "Curr Period End Date",
            "expression": "LASTDATE( DimDate[Date] )",
            "displayFolder": "_Measures\\Period Start End Dates",
            "lineageTag": "07fc552e-d608-413e-be21-8e17d8656343"
          },
          {
            "name": "Days in Curr Period",
            "expression": "DATEDIFF( [Curr Period Start Date], [Curr Period End Date], DAY )",
            "displayFolder": "_Measures\\Period Start End Dates",
            "lineageTag": "38b637b4-0269-428d-9693-65fb01195bf3"
          },
          {
            "name": "Prev Period Start Date",
            "expression": "PREVIOUSDAY( FIRSTDATE( DATEADD( DimDate[Date], -1*[Days in Curr Period], DAY ) ) )",
            "displayFolder": "_Measures\\Period Start End Dates",
            "lineageTag": "425cdbef-90bd-4fd8-b8fb-bf80e70d1151"
          },
          {
            "name": "Prev Period End Date",
            "expression": "FIRSTDATE( DATEADD( DimDate[Date], -1, DAY ) )",
            "displayFolder": "_Measures\\Period Start End Dates",
            "lineageTag": "4ecf6fee-248e-4cca-8c03-39b5b6d5b692"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Activities KPI Group",
        "lineageTag": "f4186c32-68b5-420f-84b9-828f4a94411f",
        "columns": [
          {
            "name": "Activites",
            "dataType": "string",
            "sourceColumn": "Activites",
            "lineageTag": "6fb347bb-e440-4187-a0d0-6d42e51728cb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Activities KPI Group-97a1dbe2-86a0-4d4c-b007-895860108dea",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wck7MyS/KTC1WcCotyktNUYrViVZyTC7JLMssqVSASYJFg0tSC4CsWAA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Activites = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Activites\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Sleep KPI Group",
        "lineageTag": "b33d7094-3527-488c-ba2d-9a406caa0f19",
        "columns": [
          {
            "name": "Sleep Metrics",
            "dataType": "string",
            "sourceColumn": "Sleep Metrics",
            "lineageTag": "e104cc1d-a933-4e90-a680-c962e479af4d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sleep KPI Group-4ae3627f-a3e4-479d-8ff5-353d9c8cb4e7",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8sgvLSpWcCzOSU0tUIrVgQm4ALkKwWiCjuWJ2alKsbEA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Sleep Metrics\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Sleep Metrics\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "8b8d1656-30e9-4e33-8da9-ceba826eedcf",
        "fromTable": "Sleep",
        "fromColumn": "Start Date",
        "toTable": "DimDate",
        "toColumn": "Date"
      },
      {
        "name": "7f87a36a-24c4-4990-a252-06880cb16706",
        "fromTable": "Sleep",
        "fromColumn": "End Date",
        "toTable": "DimDate",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "3ebe1b16-fea0-4e48-bf64-8485e327dd46",
        "fromCardinality": "one",
        "fromTable": "Activities",
        "fromColumn": "Date",
        "toTable": "DimDate",
        "toColumn": "Date",
        "crossFilteringBehavior": "bothDirections"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.111.590.0 (22.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Activities\",\"Sleep\",\"DimDate\",\"Activities KPI Group\",\"Sleep KPI Group\"]"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}